package interfaces;

// Records:
// - added in Java 16
// - instances are immutable
// - primary (canonical) constructor appears before the body
// - "getters" match the names of the properties, as in first(), last()
// - autogenerated equals(), hashCode(), and toString() methods
public record CompanyEmployee(String first, String last) implements Company, Employee {

    @Override
    public String getName() {
        return Employee.super.getName() + " works for " + Company.super.getName();
    }

    @Override
    public void doWork() {
        System.out.println("Converting caffeine into code for $$$");
    }
}
